export const productsData = [
  // Men's Shirts
  {
    id: 83,
    title: "Blue & Black Check Shirt",
    description:
      "The Blue & Black Check Shirt is a stylish and comfortable men's shirt featuring a classic check pattern. Made from high-quality fabric, it's suitable for both casual and semi-formal occasions.",
    category: "mens-shirts",
    price: 29.99,
    discountPercentage: 1.22,
    rating: 3.64,
    stock: 38,
    brand: "Fashion Trends",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 1, comment: "Waste of money!" },
      { rating: 5, comment: "Very satisfied!" },
      { rating: 4, comment: "Fast shipping!" },
    ],
    returnPolicy: "30 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/4.webp",
    ],
  },
  {
    id: 84,
    title: "Gigabyte Aorus Men Tshirt",
    description:
      "The Gigabyte Aorus Men Tshirt is a cool and casual shirt for gaming enthusiasts. With the Aorus logo and sleek design, it's perfect for expressing your gaming style.",
    category: "mens-shirts",
    price: 24.99,
    discountPercentage: 12.6,
    rating: 3.18,
    stock: 90,
    brand: "Gigabyte",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 5, comment: "Excellent quality!" },
      { rating: 5, comment: "Awesome product!" },
      { rating: 1, comment: "Disappointing product!" },
    ],
    returnPolicy: "30 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/4.webp",
    ],
  },
  {
    id: 85,
    title: "Man Plaid Shirt",
    description:
      "The Man Plaid Shirt is a timeless and versatile men's shirt with a classic plaid pattern. Its comfortable fit and casual style make it a wardrobe essential for various occasions.",
    category: "mens-shirts",
    price: 34.99,
    discountPercentage: 17.53,
    rating: 3.46,
    stock: 82,
    brand: "Classic Wear",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 3, comment: "Disappointing product!" },
      { rating: 4, comment: "Awesome product!" },
      { rating: 2, comment: "Very disappointed!" },
    ],
    returnPolicy: "7 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/4.webp",
    ],
  },
  {
    id: 86,
    title: "Man Short Sleeve Shirt",
    description:
      "The Man Short Sleeve Shirt is a breezy and stylish option for warm days. With a comfortable fit and short sleeves, it's perfect for a laid-back yet polished look.",
    category: "mens-shirts",
    price: 19.99,
    discountPercentage: 8.65,
    rating: 2.9,
    stock: 2,
    brand: "Casual Comfort",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "Low Stock",
    reviews: [
      { rating: 5, comment: "Highly recommended!" },
      { rating: 2, comment: "Poor quality!" },
      { rating: 1, comment: "Would not recommend!" },
    ],
    returnPolicy: "30 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/4.webp",
    ],
  },
  {
    id: 87,
    title: "Men Check Shirt",
    description:
      "The Men Check Shirt is a classic and versatile shirt featuring a stylish check pattern. Suitable for various occasions, it adds a smart and polished touch to your wardrobe.",
    category: "mens-shirts",
    price: 27.99,
    discountPercentage: 14.21,
    rating: 2.72,
    stock: 95,
    brand: "Urban Chic",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 3, comment: "Would not recommend!" },
      { rating: 5, comment: "Fast shipping!" },
      { rating: 2, comment: "Very unhappy with my purchase!" },
    ],
    returnPolicy: "30 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/4.webp",
    ],
  },

  // Men's Shoes
  {
    id: 88,
    title: "Nike Air Jordan 1 Red And Black",
    description:
      "The Nike Air Jordan 1 in Red and Black is an iconic basketball sneaker known for its stylish design and high-performance features, making it a favorite among sneaker enthusiasts and athletes.",
    category: "mens-shoes",
    price: 149.99,
    discountPercentage: 15.82,
    rating: 4.77,
    stock: 7,
    brand: "Nike",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 5, comment: "Highly impressed!" },
      { rating: 4, comment: "Very happy with my purchase!" },
      { rating: 1, comment: "Waste of money!" },
    ],
    returnPolicy: "No return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/4.webp",
    ],
  },
  {
    id: 89,
    title: "Nike Baseball Cleats",
    description:
      "Nike Baseball Cleats are designed for maximum traction and performance on the baseball field. They provide stability and support for players during games and practices.",
    category: "mens-shoes",
    price: 79.99,
    discountPercentage: 11.38,
    rating: 3.88,
    stock: 12,
    brand: "Nike",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 5, comment: "Would buy again!" },
      { rating: 2, comment: "Very disappointed!" },
      { rating: 3, comment: "Would not recommend!" },
    ],
    returnPolicy: "No return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/4.webp",
    ],
  },
  {
    id: 90,
    title: "Puma Future Rider Trainers",
    description:
      "The Puma Future Rider Trainers offer a blend of retro style and modern comfort. Perfect for casual wear, these trainers provide a fashionable and comfortable option for everyday use.",
    category: "mens-shoes",
    price: 89.99,
    discountPercentage: 14.35,
    rating: 4.9,
    stock: 90,
    brand: "Puma",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 5, comment: "Highly impressed!" },
      { rating: 1, comment: "Very disappointed!" },
      { rating: 5, comment: "Very pleased!" },
    ],
    returnPolicy: "90 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/4.webp",
    ],
  },
  {
    id: 91,
    title: "Sports Sneakers Off White & Red",
    description:
      "The Sports Sneakers in Off White and Red combine style and functionality, making them a fashionable choice for sports enthusiasts. The red and off-white color combination adds a bold and energetic touch.",
    category: "mens-shoes",
    price: 119.99,
    discountPercentage: 11.69,
    rating: 4.77,
    stock: 17,
    brand: "Off White",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 4, comment: "Would buy again!" },
      { rating: 5, comment: "Fast shipping!" },
      { rating: 5, comment: "Awesome product!" },
    ],
    returnPolicy: "30 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/4.webp",
    ],
  },
  {
    id: 92,
    title: "Sports Sneakers Off White Red",
    description:
      "Another variant of the Sports Sneakers in Off White Red, featuring a unique design. These sneakers offer style and comfort for casual occasions.",
    category: "mens-shoes",
    price: 109.99,
    discountPercentage: 17.22,
    rating: 4.69,
    stock: 62,
    brand: "Off White",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 4, comment: "Excellent quality!" },
      { rating: 5, comment: "Great value for money!" },
      { rating: 1, comment: "Not worth the price!" },
    ],
    returnPolicy: "60 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/4.webp",
    ],
  },

  // Men's Watches
  {
    id: 93,
    title: "Brown Leather Belt Watch",
    description:
      "The Brown Leather Belt Watch is a stylish timepiece with a classic design. Featuring a genuine leather strap and a sleek dial, it adds a touch of sophistication to your look.",
    category: "mens-watches",
    price: 89.99,
    discountPercentage: 15.01,
    rating: 4.19,
    stock: 32,
    brand: "Fashion Timepieces",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 1, comment: "Very unhappy with my purchase!" },
      { rating: 4, comment: "Fast shipping!" },
      { rating: 4, comment: "Would buy again!" },
    ],
    returnPolicy: "30 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/3.webp",
    ],
  },
  {
    id: 94,
    title: "Longines Master Collection",
    description:
      "The Longines Master Collection is an elegant and refined watch known for its precision and craftsmanship. With a timeless design, it's a symbol of luxury and sophistication.",
    category: "mens-watches",
    price: 1499.99,
    discountPercentage: 10.64,
    rating: 3.87,
    stock: 100,
    brand: "Longines",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 4, comment: "Highly impressed!" },
      { rating: 3, comment: "Very disappointed!" },
      { rating: 5, comment: "Great product!" },
    ],
    returnPolicy: "7 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/3.webp",
    ],
  },
  {
    id: 95,
    title: "Rolex Cellini Date Black Dial",
    description:
      "The Rolex Cellini Date with Black Dial is a classic and prestigious watch. With a black dial and date complication, it exudes sophistication and is a symbol of Rolex's heritage.",
    category: "mens-watches",
    price: 8999.99,
    discountPercentage: 16.27,
    rating: 4.97,
    stock: 40,
    brand: "Rolex",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 3, comment: "Not worth the price!" },
      { rating: 4, comment: "Very satisfied!" },
      { rating: 1, comment: "Would not buy again!" },
    ],
    returnPolicy: "90 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-date-black-dial/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-date-black-dial/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-date-black-dial/3.webp",
    ],
  },
  {
    id: 96,
    title: "Rolex Cellini Moonphase",
    description:
      "The Rolex Cellini Moonphase is a masterpiece of horology, featuring a moon phase complication and exquisite design. It reflects Rolex's commitment to precision and elegance.",
    category: "mens-watches",
    price: 12999.99,
    discountPercentage: 18.76,
    rating: 2.58,
    stock: 36,
    brand: "Rolex",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 3, comment: "Poor quality!" },
      { rating: 5, comment: "Very satisfied!" },
      { rating: 4, comment: "Very pleased!" },
    ],
    returnPolicy: "7 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/3.webp",
    ],
  },
  {
    id: 98,
    title: "Rolex Submariner Watch",
    description:
      "The Rolex Submariner is a legendary dive watch with a rich history. Known for its durability and water resistance, it's a symbol of adventure and exploration.",
    category: "mens-watches",
    price: 13999.99,
    discountPercentage: 8.84,
    rating: 2.69,
    stock: 55,
    brand: "Rolex",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 4, comment: "Great value for money!" },
      { rating: 5, comment: "Highly recommended!" },
      { rating: 5, comment: "Fast shipping!" },
    ],
    returnPolicy: "90 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/3.webp",
    ],
  },

  // Women's Dress
  {
    id: 177,
    title: "Black Women's Gown",
    description:
      "The Black Women's Gown is an elegant and timeless evening gown. With a sleek black design, it's perfect for formal events and special occasions, exuding sophistication and style.",
    category: "womens-dresses",
    price: 129.99,
    discountPercentage: 11.23,
    rating: 3.64,
    stock: 25,
    brand: "N/A",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 4, comment: "Great value for money!" },
      { rating: 3, comment: "Very dissatisfied!" },
      { rating: 5, comment: "Very satisfied!" },
    ],
    returnPolicy: "No return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/4.webp",
    ],
  },
  {
    id: 178,
    title: "Corset Leather With Skirt",
    description:
      "The Corset Leather With Skirt is a bold and edgy ensemble that combines a stylish corset with a matching skirt. Ideal for fashion-forward individuals, it makes a statement at any event.",
    category: "womens-dresses",
    price: 89.99,
    discountPercentage: 19.34,
    rating: 3.05,
    stock: 30,
    brand: "N/A",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 5, comment: "Very happy with my purchase!" },
      { rating: 4, comment: "Highly recommended!" },
      { rating: 4, comment: "Highly recommended!" },
    ],
    returnPolicy: "30 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/4.webp",
    ],
  },
  {
    id: 179,
    title: "Corset With Black Skirt",
    description:
      "The Corset With Black Skirt is a chic and versatile outfit that pairs a fashionable corset with a classic black skirt. It offers a trendy and coordinated look for various occasions.",
    category: "womens-dresses",
    price: 79.99,
    discountPercentage: 12.8,
    rating: 4.52,
    stock: 33,
    brand: "N/A",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 5, comment: "Very satisfied!" },
      { rating: 2, comment: "Disappointing product!" },
      { rating: 5, comment: "Very happy with my purchase!" },
    ],
    returnPolicy: "No return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/4.webp",
    ],
  },
  {
    id: 180,
    title: "Dress Pea",
    description:
      "The Dress Pea is a stylish and comfortable dress with a pea pattern. Perfect for casual outings, it adds a playful and fun element to your wardrobe, making it a great choice for day-to-day wear.",
    category: "womens-dresses",
    price: 49.99,
    discountPercentage: 16.65,
    rating: 4.88,
    stock: 6,
    brand: "N/A",
    shippingInformation: "Ships overnight",
    availabilityStatus: "Low Stock",
    reviews: [
      { rating: 4, comment: "Fast shipping!" },
      { rating: 1, comment: "Not worth the price!" },
      { rating: 2, comment: "Would not buy again!" },
    ],
    returnPolicy: "90 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/4.webp",
    ],
  },
  {
    id: 181,
    title: "Marni Red & Black Suit",
    description:
      "The Marni Red & Black Suit is a sophisticated and fashion-forward suit ensemble. With a combination of red and black tones, it showcases a modern design for a bold and confident look.",
    category: "womens-dresses",
    price: 179.99,
    discountPercentage: 14.11,
    rating: 4.48,
    stock: 62,
    brand: "Marni",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 5, comment: "Fast shipping!" },
      { rating: 3, comment: "Very disappointed!" },
      { rating: 4, comment: "Highly impressed!" },
    ],
    returnPolicy: "90 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/4.webp",
    ],
  },

  // Women's Bags
  {
    id: 172,
    title: "Blue Women's Handbag",
    description:
      "The Blue Women's Handbag is a stylish and spacious accessory for everyday use. With a vibrant blue color and multiple compartments, it combines fashion and functionality.",
    category: "womens-bags",
    price: 49.99,
    discountPercentage: 8.08,
    rating: 2.92,
    stock: 76,
    brand: "Fashionista",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 3, comment: "Waste of money!" },
      { rating: 3, comment: "Not worth the price!" },
      { rating: 4, comment: "Highly impressed!" },
    ],
    returnPolicy: "7 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/3.webp",
    ],
  },
  {
    id: 173,
    title: "Heshe Women's Leather Bag",
    description:
      "The Heshe Women's Leather Bag is a luxurious and high-quality leather bag for the sophisticated woman. With a timeless design and durable craftsmanship, it's a versatile accessory.",
    category: "womens-bags",
    price: 129.99,
    discountPercentage: 10.22,
    rating: 4.92,
    stock: 99,
    brand: "Heshe",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 5, comment: "Excellent quality!" },
      { rating: 4, comment: "Awesome product!" },
      { rating: 4, comment: "Awesome product!" },
    ],
    returnPolicy: "90 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/womens-bags/heshe-women's-leather-bag/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/heshe-women's-leather-bag/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/heshe-women's-leather-bag/3.webp",
    ],
  },
  {
    id: 174,
    title: "Prada Women Bag",
    description:
      "The Prada Women Bag is an iconic designer bag that exudes elegance and luxury. Crafted with precision and featuring the Prada logo, it's a statement piece for fashion enthusiasts.",
    category: "womens-bags",
    price: 599.99,
    discountPercentage: 12.1,
    rating: 2.71,
    stock: 75,
    brand: "Prada",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 2, comment: "Would not buy again!" },
      { rating: 4, comment: "Great value for money!" },
      { rating: 5, comment: "Highly recommended!" },
    ],
    returnPolicy: "60 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/3.webp",
    ],
  },
  {
    id: 175,
    title: "White Faux Leather Backpack",
    description:
      "The White Faux Leather Backpack is a trendy and practical backpack for the modern woman. With a sleek white design and ample storage space, it's perfect for both casual and on-the-go styles.",
    category: "womens-bags",
    price: 39.99,
    discountPercentage: 15.91,
    rating: 3.36,
    stock: 39,
    brand: "Urban Chic",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 4, comment: "Awesome product!" },
      { rating: 1, comment: "Not as described!" },
      { rating: 5, comment: "Great value for money!" },
    ],
    returnPolicy: "90 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/3.webp",
    ],
  },
  {
    id: 176,
    title: "Women Handbag Black",
    description:
      "The Women Handbag in Black is a classic and versatile accessory that complements various outfits. With a timeless black color and functional design, it's a must-have in every woman's wardrobe.",
    category: "womens-bags",
    price: 59.99,
    discountPercentage: 17.3,
    rating: 2.89,
    stock: 11,
    brand: "Elegance Collection",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 4, comment: "Very pleased!" },
      { rating: 5, comment: "Great product!" },
      { rating: 1, comment: "Waste of money!" },
    ],
    returnPolicy: "60 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/womens-bags/women-handbag-black/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/women-handbag-black/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/women-handbag-black/3.webp",
    ],
  },

  // Women's Shoes
  {
    id: 185,
    title: "Black & Brown Slipper",
    description:
      "The Black & Brown Slipper is a comfortable and stylish choice for casual wear. Featuring a blend of black and brown colors, it adds a touch of sophistication to your relaxation.",
    category: "womens-shoes",
    price: 19.99,
    discountPercentage: 12.28,
    rating: 2.53,
    stock: 3,
    brand: "Comfort Trends",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "Low Stock",
    reviews: [
      { rating: 5, comment: "Highly impressed!" },
      { rating: 2, comment: "Not worth the price!" },
      { rating: 4, comment: "Very happy with my purchase!" },
    ],
    returnPolicy: "60 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/4.webp",
    ],
  },
  {
    id: 186,
    title: "Calvin Klein Heel Shoes",
    description:
      "Calvin Klein Heel Shoes are elegant and sophisticated, designed for formal occasions. With a classic design and high-quality materials, they complement your stylish ensemble.",
    category: "womens-shoes",
    price: 79.99,
    discountPercentage: 11.16,
    rating: 4.92,
    stock: 93,
    brand: "Calvin Klein",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 5, comment: "Great value for money!" },
      { rating: 5, comment: "Great value for money!" },
      { rating: 1, comment: "Not as described!" },
    ],
    returnPolicy: "60 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/4.webp",
    ],
  },
  {
    id: 187,
    title: "Golden Shoes Woman",
    description:
      "The Golden Shoes for Women are a glamorous choice for special occasions. Featuring a golden hue and stylish design, they add a touch of luxury to your outfit.",
    category: "womens-shoes",
    price: 49.99,
    discountPercentage: 14.97,
    rating: 3.26,
    stock: 88,
    brand: "Fashion Diva",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 4, comment: "Excellent quality!" },
      { rating: 5, comment: "Very pleased!" },
      { rating: 4, comment: "Very pleased!" },
    ],
    returnPolicy: "7 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/4.webp",
    ],
  },
  {
    id: 188,
    title: "Pampi Shoes",
    description:
      "Pampi Shoes offer a blend of comfort and style for everyday use. With a versatile design, they are suitable for various casual occasions, providing a trendy and relaxed look.",
    category: "womens-shoes",
    price: 29.99,
    discountPercentage: 8.42,
    rating: 3.05,
    stock: 49,
    brand: "Pampi",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      { rating: 4, comment: "Great product!" },
      { rating: 3, comment: "Very disappointed!" },
      { rating: 1, comment: "Would not buy again!" },
    ],
    returnPolicy: "30 days return policy",
    images: [
      "https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/3.webp",
    ],
  },
];
